### ISSUE TITLE
Confusing behaviour when trying to change email address

### ISSUE THREAD

**Issue by sjelfull** [pixelandtonic/craftcom#10]
Without entering my current password, there is the expected server error "Password must be a string and cannot be empty", but 1) It's returned as HTML 2) The site does not give any feedback that it happened. I had to check the console.

With entering my current password, it now works. However, it just says "Settings saved".

I was not receiving the "Verify new email address yesterday", so I was confused since it didn't actually change the email.

It should probably say "You will a email to activate your new email address soon" or something like that.

**Comment by benjamindavid** [comment]
This behavior has been improved. Thanks for reporting @sjelfull!
