### ISSUE TITLE
Bad URL route for plugin doesn't redirect / error

### ISSUE THREAD

**Issue by mildlygeeky** [pixelandtonic/craftcom#14]
Steps to reproduce:

- Go to id.craftcms.com/developer/plugins/{anything - number, text, whatever}
- See empty form fields for plugin (hopefully I cannot save this form and overwrite someone else's plugin if I supplied their ID - I don't think I can)

Expected results:
- Would get some error message and/or be redirected back to id.craftcms.com/developer/plugins

**Comment by benjamindavid** [comment]
You will now be redirected to `/developer/plugins`. Thanks for pointing this out!
