### ISSUE TITLE
Vue on RC1 is running in development mode

### ISSUE THREAD

**Issue by mildlygeeky** [pixelandtonic/craftcom#15]
This may be intentional, as it is still a release candidate, but running in dev / non-minified mode does have performance implications and allows people to snoop around with Vue Dev Tools

**Comment by benjamindavid** [comment]
Huh, that's weird. Are you able to browse the data in the Vue Devtools? It shows production mode on my side.

**Comment by mildlygeeky** [comment]
Sorry, this should have been put into the CMS repo, as it is running dev mode in the RC1 plugin store itself. Do you want me to re-open there, or is this OK?

**Comment by benjamindavid** [comment]
We've actually moved Vue.js to a Vue asset bundle which was using the unminified version of the lib, aimed at development.  Fixed by https://github.com/craftcms/cms/commit/63ed1f067594511257415919f5a0f81aaffa6f3d.
Thanks for the feedback!
