### ISSUE TITLE
Cannot upload animated gif… server 500 error.

### ISSUE THREAD

**Issue by leevigraham** [pixelandtonic/craftcom#16]
The gif: ![embed-demo](https://user-images.githubusercontent.com/25124/33530066-e52e6cae-d8cd-11e7-8979-fe852b076114.gif)

The response: fopen(/efs/storage-web/runtime/temp/screenshot-nsm-fields-OiPYoqIznxB5qZXELlnKRb8JAbltdu7cXQ0x.gif): failed to open stream: No such file or directory

**Comment by takobell** [comment]
Misleading error message aside, this is coming from the fact that the image is bumping up against the default php.ini file upload size of 2MB.

@benjamindavid we should limit screenshots to PNG and JPG only. 

We should also run the uploaded image through [`services/Image->checkMemoryForImage()`](https://github.com/craftcms/cms/blob/develop/src/services/Images.php#L219), which will look at the given image, see how much memory it would need to load it and check against both php.ini file upload size as well as Craft's maxUploadFileSize config setting and return if it thinks it will be possible.  We should gracefully return a validation error if it's not going to happen.

**Comment by leevigraham** [comment]
bq. @benjamindavid we should limit screenshots to PNG and JPG only.

I realise .gifs could be open to abuse but they are a great way to show interactivity and advancd functionality.

**Comment by brandonkelly** [comment]
@leevigraham I think I’d rather allow a Vimeo/YouTube embed than animated GIFs, to avoid auto-playing animations, and because streaming mp4s are better on bandwidth than animated GIFs.

**Comment by benjamindavid** [comment]
id.craftcms.com should now be taking into account upload size and memory limitations, and only accept PNG and JPG for screenshots.
