### ISSUE TITLE
Be able to specify or suggest plugin categories

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#18]
I'd like a way to suggest categories for plugins; for instance, ImageOptimize should probably be under “performance” as well

**Comment by brandonkelly** [comment]
@benjamindavid Maybe we can add a “Suggested Categories” field that is only visible for disabled plugins. Once a plugin has been approved, it goes away.

**Comment by khalwat** [comment]
FWIW, for the Apple Store, you get to pick the categories, but you only get to pick 3.

**Comment by brandonkelly** [comment]
Interesting.

**Comment by benjamindavid** [comment]
You should now be able to pick up to 3 categories for your plugins.

Thanks for the feedback @khalwat!
