### ISSUE TITLE
Sitemap shows the wrong sitemap plugin

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#27]
I'm assuming because the plugin handle is just `sitemap`, but on a Craft 2.x site that has Ben Croker's Sitemap plugin installed, I see this:

![finderscreensnapz043](https://user-images.githubusercontent.com/7570798/34207766-d6b572f6-e559-11e7-8b70-c2a1d9bd69c4.png)

...which is Dolphiq's "XML Sitemap" plugin

**Comment by ryanmasuga** [comment]
I'm seeing this same thing.

![image](https://user-images.githubusercontent.com/988995/34226147-c85e1040-e596-11e7-801d-41ad73f2d028.png)
