### ISSUE TITLE
Upload a photo

### ISSUE THREAD

**Issue by ostark** [pixelandtonic/craftcom#3]
After selecting a photo from my drive, the spinner loops forever and the placeholder is not replaced by the uploaded photo. 
After page reload the photo is there.

**Comment by svenjungnickel** [comment]
Yes got the same issue.

**Comment by brandonkelly** [comment]
Which photos are you referring to? User photos? Plugin icon? Screenshot?

We can't reproduce, and looks like you both have uploaded user photos.

**Comment by svenjungnickel** [comment]
It is the user photo. I’m not sure if this issue still occurs. The photo was uploaded but wasn’t shown after the upload. Only after reloading the page. Seems to be a a UI problem.

**Comment by brandonkelly** [comment]
What browser are you using?

**Comment by ostark** [comment]
I was able to reproduce it, but not anymore.
