### ISSUE TITLE
Procedure for changing package names

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#30]
So to get in line with the package / branch naming [as discussed here](https://craftcms.stackexchange.com/questions/23535/craft-3-plugin-backwards-compatibility-and-maintenance-for-2-x) I'm planning to:

1. Rename all of my github repos from `craft3-` to `craft-`
2. Create a branch `v1` or `v2` or `v2` to indicate the plugin's version, and get rid of the `master` branch
3. Deprecate the old packagist.org packages and create new ones [as per the procedure here](https://github.com/composer/packagist/issues/47)
4. Update my `composer.json` files to reflect the new package name
5. Somehow update the existing plugins in the Craft plugin store to point to the new repos, but keep the same plugin handle, and everything else.

1 & 2 are no brainers, and easy to do because Github will automatically redirect from the old repo name. 3, 4 & 5 are somewhat troublesome, in that there's a bit of work (which is fine), but also anyone who already has one of the plugins installed will be stuck with a deprecated repo.

So before I embark on this, I want to make sure that I'm not making a critical error in renaming everything. Should I just not bother with 3, 4 & 5? Are there any gotchas on the Craft plugin store side of things I should take into consideration?

I feel like if I'm going to do this, I should do it now, or not at all.

**Comment by brandonkelly** [comment]
Just let us know when you’ve released a new version of your plugins with an updated package name, and we’ll update the caches on our end. People that have your plugin installed will just need to manually `composer remove` your plugin, and then re-install it from the Plugin Store or Composer, after it’s done.

**Comment by khalwat** [comment]
I guess my real question was whether it made sense to go through renaming the packagist.org package if the end-user will (usually) never even see it.

I just don't want to make a big hassle for everyone for no reason.

**Comment by brandonkelly** [comment]
It’s totally up to you, but if you’re going to change it, now’s definitely better than later, like when Craft 4 comes out.
