### ISSUE TITLE
Update Plugin Package Name

### ISSUE THREAD

**Issue by mikestecker** [pixelandtonic/craftcom#33]
I went through and updated my two little plugins after reading what @khalwat was doing in #30. Can you update my listings in the Plugin Store to reflect this change?

The plugins are: Readability & Video Embedder. Video Embedder is in my developer area but not listed as public yet. I just need the composer package name to drop the `3` from `craft3-[pluginname]`. I have already gone through and "abandoned" each package and created new ones plus updated everything on my end that I can do reflect the changes.

Thanks!

**Comment by brandonkelly** [comment]
Done! Updated the repo URLs as well.
