### ISSUE TITLE
ImageOptimize plugin package name/url changed

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#34]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `image-optimize`

Old package name: `nystudio107/craft3-imageoptimize`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-imageoptimize
Old GitHub URL: https://github.com/nystudio107/craft3-imageoptimize

New package name: `nystudio107/craft-imageoptimize`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-imageoptimize
New GitHub URL: https://github.com/nystudio107/craft-imageoptimize

**Comment by brandonkelly** [comment]
Done 👍 

You probably have two webhooks in your repo settings now - one of them will start returning non-200 responses, and you can delete that one.

**Comment by khalwat** [comment]
Deleted it, thanks!
