### ISSUE TITLE
Cookies plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#36]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `cookies`

Old package name: `nystudio107/craft3-cookies `
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-cookies
Old GitHub URL: https://github.com/nystudio107/craft3-cookies

New package name: `nystudio107/craft-cookies`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-cookies
New GitHub URL: https://github.com/nystudio107/craft-cookies

**Comment by brandonkelly** [comment]
👍
