### ISSUE TITLE
Disqus plugin package name/url changed

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#37]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `disqus`

Old package name: `nystudio107/craft3-disqus `
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-disqus
Old GitHub URL: https://github.com/nystudio107/craft3-disqus

New package name: `nystudio107/craft-disqus `
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-disqus
New GitHub URL: https://github.com/nystudio107/craft-disqus

**Comment by brandonkelly** [comment]
👍
