### ISSUE TITLE
Eager Beaver plugin package name/url changed

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#38]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `eagerbeaver`

Old package name: `nystudio107/craft3-eagerbeaver `
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-eagerbeaver
Old GitHub URL: https://github.com/nystudio107/craft3-eagerbeaver

New package name: `nystudio107/craft-eagerbeaver `
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-eagerbeaver
New GitHub URL: https://github.com/nystudio107/craft-eagerbeaver

**Comment by brandonkelly** [comment]
👍
