### ISSUE TITLE
FastCGI Cache Bust plugin package name/url changed

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#39]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `fastcgicachebust`

Old package name: `nystudio107/craft3-fastcgicachebust`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-fastcgicachebust
Old GitHub URL: https://github.com/nystudio107/craft3-fastcgicachebust

New package name: `nystudio107/craft-fastcgicachebust`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-fastcgicachebust
New GitHub URL: https://github.com/nystudio107/craft-fastcgicachebust

**Comment by brandonkelly** [comment]
👍
