### ISSUE TITLE
Can not update plugin details

### ISSUE THREAD

**Issue by svenjungnickel** [pixelandtonic/craftcom#4]
I tried to update the plugin details, uploaded a screenshot and changed the documentationand  changelog path. But after hitting the submit button the spinner loops a while and then I got the error message **Couldn't save plugin**

**Comment by janhenckens** [comment]
Same issue here, although the changes I make & the screenshots I upload are being saved.

**Comment by brandonkelly** [comment]
Not able to reproduce this, so I’m assuming it has been fixed. Let me know if either of you are still seeing it, though.

**Comment by svenjungnickel** [comment]
@brandonkelly just tried to update the long description but got the same error message again. The issue obviously still exists.

**Comment by brandonkelly** [comment]
@svenjungnickel Which plugin?

**Comment by svenjungnickel** [comment]
It is the **Redactor Font Awesome** plugin. However I was able to update all the other details I mentioned already, including the icon.

I reckon this problem only occurs when certain fields are not filled.

**Comment by svenjungnickel** [comment]
Just did some more tests. Its kinda of bizarre.
The error message comes up on mobile, chrome as well as safari. The changes are not displayed on mobile. But when I load it on the desktop version it shows me the changes I made mobile. I also can make changes on the desktop and it saves without an error.

**Comment by brandonkelly** [comment]
Awesome thanks. Sounds like a UI bug, then.

**Comment by benjamindavid** [comment]
It looks like the bug happens with browsers providing partial support for FormData. Fix upcoming!

**Comment by mildlygeeky** [comment]
Per a discussion with Brandon this morning, I was still encountering this error today. Looks like the server is getting a 500 error, with a SQL syntax bug being reported on the ajax call.

**Comment by NathanHeffley** [comment]
I am having this issue with my plugin, contact-form-drip. I can't update any information. No matter what I change (or if I don't change anything) I can't save my plugin info. If I can submit specific info to help you test this I'd be more than happy to help.

**Comment by brandonkelly** [comment]
This should be fixed now.
