### ISSUE TITLE
Instant Analytics plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#40]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `instantanalytics`

Old package name: `nystudio107/craft3-instantanalytics`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-instantanalytics
Old GitHub URL: https://github.com/nystudio107/craft3-instantanalytics

New package name: `nystudio107/craft-instantanalytics`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-instantanalytics
New GitHub URL: https://github.com/nystudio107/craft-instantanalytics

**Comment by brandonkelly** [comment]
👍
