### ISSUE TITLE
Minify plugin package name/url changed

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#41]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `minify`

Old package name: `nystudio107/craft3-minify `
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-minify
Old GitHub URL: https://github.com/nystudio107/craft3-minify

New package name: `nystudio107/craft-minify `
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-minify
New GitHub URL: https://github.com/nystudio107/craft-minify

**Comment by brandonkelly** [comment]
👍
