### ISSUE TITLE
PathTools plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#42]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `pathtools`

Old package name: `nystudio107/craft3-pathtools`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-pathtools
Old GitHub URL: https://github.com/nystudio107/craft3-pathtools

New package name: `nystudio107/craft-pathtools`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-pathtools
New GitHub URL: https://github.com/nystudio107/craft-pathtools

**Comment by brandonkelly** [comment]
👍
