### ISSUE TITLE
Recipe plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#43]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `recipe`

Old package name: `nystudio107/craft3-recipe `
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-recipe
Old GitHub URL: https://github.com/nystudio107/craft3-recipe

New package name: `nystudio107/craft-recipe `
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-recipe
New GitHub URL: https://github.com/nystudio107/craft-recipe

**Comment by brandonkelly** [comment]
👍
