### ISSUE TITLE
Rich Variables plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#44]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `richvariables`

Old package name: `nystudio107/craft3-richvariables`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-richvariables
Old GitHub URL: https://github.com/nystudio107/craft3-richvariables

New package name: `nystudio107/craft-richvariables`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-richvariables
New GitHub URL: https://github.com/nystudio107/craft-richvariables

**Comment by brandonkelly** [comment]
👍
