### ISSUE TITLE
Route Map plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#45]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `routemap`

Old package name: `nystudio107/craft3-routemap`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-routemap
Old GitHub URL: https://github.com/nystudio107/craft3-routemap

New package name: `nystudio107/craft-routemap`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-routemap
New GitHub URL: https://github.com/nystudio107/craft-routemap

**Comment by brandonkelly** [comment]
👍
