### ISSUE TITLE
Transcoder plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#46]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `transcoder`

Old package name: `nystudio107/craft3-transcoder`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-transcoder
Old GitHub URL: https://github.com/nystudio107/craft3-transcoder

New package name: `nystudio107/craft-transcoder`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-transcoder
New GitHub URL: https://github.com/nystudio107/craft-transcoder

**Comment by brandonkelly** [comment]
👍
