### ISSUE TITLE
Typogrify plugin package name/url changed 

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftcom#47]
As part of my purge removing `craft3-` as a package prefix, and changing it to: `craft-`, the following plugin has been changed, and needs to be update in the Craft Plugin Store:

Plugin handle: `typogrify`

Old package name: `nystudio107/craft3-typogrify`
Old Packagist.org URL: https://packagist.org/packages/nystudio107/craft3-typogrify
Old GitHub URL: https://github.com/nystudio107/craft3-typogrify

New package name: `nystudio107/craft-typogrify`
New Packagist.org URL: https://packagist.org/packages/nystudio107/craft-typogrify
New GitHub URL: https://github.com/nystudio107/craft-typogrify

**Comment by brandonkelly** [comment]
👍
